apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80         # Port that the Service exposes
      targetPort: 80   # Port on the container that the Service will forward to
  type: LoadBalancer  # Exposes the service via an external LoadBalancer
